build:
	docker compose build

run:
	docker compose run --rm tart2ms bash

# The repository is mounted at /tart2ms in the container, e.g.
#    docker compose run --rm tart2ms tart2ms --hdf /tart2ms/test_data/<file>.hdf --ms /tart2ms/test.ms
